version: 0.2
phases:
  install:
    commands:
      - "npm install"
      - "npm run preinstall"
  build:
    commands:
      - "tsc"
artifacts:
  type: zip
  files:
    - package.json
    - package-lock.json
    - appspec.yml
    - "**/*"
    - README.md
